version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: notes
      POSTGRES_PASSWORD: "Vp267kKKbCpTRusuyhqHTAGfN0BBrWnu"
    volumes:
      - notes_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "Xh-xHk2sb_YhNKLVvHjv5YClXr2y2K09"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  notes_data:
